### ISSUE TITLE
Exceptions when multiple downloads are active

### ISSUE THREAD

**Issue by sridhard** [EkoLabs/react-native-background-downloader#18]
Hi,

When using rn-background-downloader for multiple parallel downloads we are getting the below exceptions:

Exception-1:
------------------
05-06 08:25:04.171 10860 10860 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.eko.RNBGDTaskConfig.id' on a null object reference
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at com.eko.RNBackgroundDownloaderModule.onCompleted(RNBackgroundDownloaderModule.java:276)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at com.tonyodev.fetch2.fetch.ListenerCoordinator$mainListener$1$onCompleted$$inlined$synchronized$lambda$2.run(ListenerCoordinator.kt:246)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6388)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
05-06 08:25:04.171 10860 10860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

Exception-2
------------------------ 
We are also getting concurrent-modification-exception. I forget to capture exception trace.
This is because requestIdToConfig and idToRequestId are accessed from 2 threads(One is from react thread and other is from the fetch thread where responses are received) without any synchronization

**Comment by ptelad** [comment]
Hi,
Can you please give more details on how you got to these exceptions?
Like:

- How come your `RNBGDTaskConfig` was null?
- How come both threads were trying to change the same collection?

Please supply things like code snippets and maybe an overall explanation of your flow.

Thank you.

**Comment by ptelad** [comment]
This issue is inactive for too long.

**Comment by learnyst** [comment]
Hi,

In react-native-background-downloader there are multiple maps like requestIdToConfig, idToRequestId in both IOS and android. RNBackgroundDownloader uses fetch2 in android and NSUrlSession in IOS for the download.

When the application using RNBackgroundDownloader calls api-methods like download, checkforexistingdownloads, pause etc it will happen in JS thread or in a seperate queue in IOS. These api-methods will modify the maps.

When the fetch2/NSUrlSession start download, it will give the progress and completed events. These events will NOT be handled in the same thread as the api-method threads. But the methods in these events also will modify the maps.

In summary react-native-background-downloader has multiple maps. These maps are accessed/modified from multiple threads with out synchronization. This will lead to exception.

Example: Start a download. When the download is in progress cancel the download. Progress event and cancel-api are handled in different methods. When both progress event and cancel occur at same time, both will access/modify the maps which will lead to exception.

In android I have put the locks for the maps. The problem will be resolved if we add maps. 

I have checked IOS code also. In IOS also the maps are not protected. In IOS taskToConfigMap is protected but other maps like idToTaskMap is not protected. PR #44 proposes to remove the synchronized access for taskToConfigMap. But the synchronized access is required. MethodQueue will delegate the api-method calls on the same thread and this is handled by react. But the NSSession callbacks can happen in another thread. So the maps need protection in IOS also.

In production we have found multiple crashes in android. After adding the synchronized access the issue is resolved. IOS also we found few crashes(We have used the code before synchronized access is added for taskToConfigMap).
