### ISSUE TITLE
How do I know that the download has paused?

### ISSUE THREAD

**Issue by dwqyun** [EkoLabs/react-native-background-downloader#8]
hello.

A task download, use the 'paue()' api to pause task , but no callback methods,
how to accurately know that the task has paused, then i can update the state of task to interface.
I use setTimeout to delayed update state, but not very accurate.

thanks

**Comment by ptelad** [comment]
I’m not sure I follow - how is your use case different from performing pause() then instantly updating your UI? That’s how we achieve this

**Comment by angelos3lex** [comment]
@ptelad if you see on android code on module there is a method:
```
  @Override
  public void onPaused(Download download) {

}

```
which is not implemented. If you implement it so that when it fires, the pause() react method resolves would be what the op is asking.
Though i am searching the same on ios side, and it seems like  NSURLSessionTaskState state has no callbacks like onCanceled onPaused etc, it's just a read only property. Maybe a proposed solution (though i don't think is the best) would be to:
after we do:
```
if (task != nil && task.state == NSURLSessionTaskStateRunning) {
        [task suspend];
        while(task.state != NSURLSessionTaskStateSuspended){ //until state matches the suspended
             sleep(0.1 sec) 
        }
       and here: resolve promise 
}
```

**Comment by ptelad** [comment]
@angelos3lex since the library was written first for iOS, where `onPause` was not an option, the Android version followed suit to maintain the same API.

I'd be happy to accept a pull request with this feature added.
